### ISSUE TITLE
Environment Variables Not Being Loaded from `.env` File

### ISSUE THREAD

**Issue by pneumaticos** [Saverious/daraja#3]
#### Description
I am having trouble with environment variables not being read from the `.env` file in the project. Despite following several troubleshooting steps, the variables are coming through as `undefined`.

#### Steps to Reproduce
1. Clone the repository.
2. Add a `.env` file in the root directory with the following content:
3. Run the script with `node payment`.

#### What I Expected
The environment variables should be loaded and available in `process.env`.

#### What Happened
All environment variables are `undefined`, and the script fails with a missing arguments error.

#### Troubleshooting Steps Taken
- Verified `.env` file format and placement.
- Ensured `dotenv` package is installed and required correctly.
- Checked for typos and syntax errors.
- Tested in a minimal Node.js environment.

#### Code Example
```javascript
require('dotenv').config();
const Daraja = require('../index');
const { CONSUMER_KEY, CONSUMER_SECRET, PHONE, CALLBACK } = process.env;

console.log('Environment Variables:', { CONSUMER_KEY, CONSUMER_SECRET, PHONE, CALLBACK });

Payment error: Error: Missing required arguments: consumer_key, consumer_secret

**Comment by Saverious** [comment]
The issue is probably due to how **dotenv** handles reading of .env files.  "dotenv" checks for the .env file in the current working directory. Try to move your .env file to the test folder and see if this resolves the issue. Alternatively, you can define the path to your .env file as follows:

`require('dotenv').config({path: '../.env'})`

**Comment by Saverious** [comment]
Visit the suggestion below:
https://github.com/Saverious/daraja/issues/3#issuecomment-2356597637

**Comment by pneumaticos** [comment]
That resolved the issue. I'm still in shock that I didn't think of that. Thank you, kind sir.
